# Generated by Django 6.0.5 on 2026-05-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('penulis', models.CharField(max_length=100)),
                ('kategori', models.CharField(choices=[('Berita Tim', 'Berita Tim'), ('Analisis Balapan', 'Analisis Balapan'), ('Pembaruan Teknis', 'Pembaruan Teknis'), ('Opini Fans', 'Opini Fans')], default='Berita Tim', max_length=50)),
                ('ringkasan', models.TextField(help_text='Ringkasan singkat artikel', max_length=500)),
                ('konten', models.TextField()),
                ('gambar_url', models.URLField(blank=True, help_text='Link URL gambar artikel', max_length=500)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Daftar Artikel',
                'ordering': ['-tanggal_dibuat'],
            },
        ),
    ]
