# Generated by Django 5.0.14 on 2026-06-03 08:07

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify

def migrate_categories(apps, schema_editor):
    Kategori = apps.get_model('artikel', 'Kategori')
    
    # Pre-populate the 4 default categories
    default_cats = ['Berita Tim', 'Analisis Balapan', 'Pembaruan Teknis', 'Opini Fans']
    cat_objs = {}
    for name in default_cats:
        obj, created = Kategori.objects.get_or_create(
            nama=name,
            defaults={'slug': slugify(name)}
        )
        cat_objs[name] = obj

    # Safely migrate old category strings to the new foreign keys
    from django.db import connection
    with connection.cursor() as cursor:
        # Get column names to see if we have kategori or kategori_id
        cursor.execute("PRAGMA table_info(artikel_artikel)")
        columns = [col[1] for col in cursor.fetchall()]
        col_to_use = 'kategori_id' if 'kategori_id' in columns else 'kategori'
        
        cursor.execute(f"SELECT id, {col_to_use} FROM artikel_artikel")
        rows = cursor.fetchall()
        for row in rows:
            art_id, old_val = row
            # If the old value is a string and matches one of our categories, update it to the ID
            if isinstance(old_val, str) and old_val in cat_objs:
                fk_id = cat_objs[old_val].id
                cursor.execute(
                    f"UPDATE artikel_artikel SET {col_to_use} = %s WHERE id = %s",
                    [fk_id, art_id]
                )

class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Daftar Kategori',
            },
        ),
        migrations.AlterField(
            model_name='artikel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikels', to='artikel.kategori'),
        ),
        migrations.RunPython(migrate_categories, reverse_code=migrations.RunPython.noop),
    ]
