# Generated by Django 6.0.5 on 2026-05-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Helm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pembalap', models.CharField(max_length=100)),
                ('judul_desain', models.CharField(max_length=200)),
                ('tahun', models.IntegerField()),
                ('sasis', models.CharField(max_length=50)),
                ('balapan_berkesan', models.CharField(max_length=200)),
                ('gambar_url', models.URLField(help_text='Link URL gambar helm', max_length=500)),
                ('deskripsi', models.TextField()),
            ],
            options={
                'verbose_name': 'Helm Pembalap',
                'verbose_name_plural': 'Daftar Helm Pembalap',
                'ordering': ['-tahun'],
            },
        ),
    ]
